config/routes.rb
Rails.application.routes.draw do
  resources :friends
  devise_for :users
  root to: "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/friends/_form.html.haml
= form_for @friend do |f|
  - if @friend.errors.any?
    #error_explanation
      %h2= "#{pluralize(@friend.errors.count, "error")} prohibited this friend from being saved:"
      %ul
        - @friend.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :phone
    = f.text_field :phone
  .field
    = f.label :twitter
    = f.text_field :twitter
  .actions
    = f.submit 'Save'

app/views/friends/edit.html.haml
%h1 Editing friend

= render 'form'

= link_to 'Show', @friend
\|
= link_to 'Back', friends_path

app/views/friends/index.html.haml
%h1 Listing friends

%table
  %thead
    %tr
      %th First name
      %th Last name
      %th Email
      %th Phone
      %th Twitter
      %th
      %th
      %th

  %tbody
    - @friends.each do |friend|
      %tr
        %td= friend.first_name
        %td= friend.last_name
        %td= friend.email
        %td= friend.phone
        %td= friend.twitter
        %td= link_to 'Show', friend
        %td= link_to 'Edit', edit_friend_path(friend)
        %td= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Friend', new_friend_path

app/views/friends/new.html.haml
%h1 New friend

= render 'form'

= link_to 'Back', friends_path

app/views/friends/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @friend.first_name
%p
  %b Last name:
  = @friend.last_name
%p
  %b Email:
  = @friend.email
%p
  %b Phone:
  = @friend.phone
%p
  %b Twitter:
  = @friend.twitter

= link_to 'Edit', edit_friend_path(@friend)
\|
= link_to 'Back', friends_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title A
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/pages/about.html.haml
%h1 Pages#about
%p Find me in app/views/pages/about.html.haml

app/views/pages/contact.html.haml
%h1 Pages#contact
%p Find me in app/views/pages/contact.html.haml

app/views/pages/index.html.haml
%h1 Pages#index
%p Find me in app/views/pages/index.html.haml